FROM python:3.13.2-slim-bookworm

# timezone
RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# apt
RUN apt-get update && \
    apt-get install -y python-is-python3

# python
WORKDIR /app/
RUN pip install --upgrade pip
COPY main/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt