services:
  main:
    container_name: "d2m_main"
    user: "${USER_NAME}"
    build:
      context: "."
      dockerfile: ./docker/main/dockerfile
      args:
        GID: "${GID}"
        UID: "${UID}"
        USER_NAME: "${USER_NAME}"
    volumes:
      - ./main:/app
      - /:/mnt:ro
    tty: true
