# 全体の設定
[global]
# ディスク使用率通知の下限
diskUsageMaxLimit = 80

# メールの送り先
toMail = ""
# メールの送り主
fromMail = ""

# 監視する対象のdiskの名前(なんでもよい)
[disk 1]
# dfで表示される一番右の部分
mountPath="/path/to/disk"
# 書かれているなら優先
diskUsageMaxLimit = 50

[disckr]

mountPath="/path/to/disk"
diskUsageMaxLimit= 10
